http.host=![u6Sevq3Ag4+6qL6ONIrJsA==]
http.port=![aQbR5O6T+0o=]
db.host=![u6Sevq3Ag4+6qL6ONIrJsA==]
db.port=![uxtgluD4taU=]
db.username=![/kUqTQeeAZQ=]
db.password=![/kUqTQeeAZQ=]
jms.username=![ww4ImFS2DOA=]
jms.password=![ww4ImFS2DOA=]
jms.broker_url=![AvAXIbGVExiyaAF/muES54NGqJpAs/W+]
